In [64]:
import pandas as pd

#read excel file into pandas dataframe
df = pd.read_excel('C:/Users/dtgiv/Projects/Data/2023_rookie_offensive_stats.xls')

df.head(20)

,Rk,Name,Yrs,From,To,ASG,WAR/pos,G,PA,AB,...,BB,SO,BA,OBP,SLG,OPS,Debut,Age,Pos Summary,Tm
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN
1,1.0,Andrew Abbott,1.0,2023.0,2023.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2023-06-05,24.0,/1,CIN
2,2.0,Wilyer Abreu,1.0,2023.0,2023.0,0.0,0.8,28.0,85.0,76.0,...,9.0,23.0,0.316,0.388,0.474,0.862,2023-08-22,24.0,/87H9D,BOS
3,3.0,Garrett Acton,1.0,2023.0,2023.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-14,25.0,/1,OAK
4,4.0,Jordyn Adams,1.0,2023.0,2023.0,0.0,-0.7,17.0,40.0,39.0,...,0.0,16.0,0.128,0.125,0.128,0.253,2023-08-02,23.0,/98H7,LAA
5,5.0,Ty Adcock,1.0,2023.0,2023.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,2023-06-12,26.0,/1,SEA
6,6.0,Ryan Aguilar,1.0,2022.0,2022.0,0.0,-0.3,7.0,26.0,22.0,...,2.0,14.0,0.136,0.231,0.182,0.413,2022-08-26,28.0,/9738,NaN
7,7.0,Cam Alldred,1.0,2022.0,2022.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,2022-05-12,26.0,/1,NaN
8,8.0,Logan Allen,1.0,2023.0,2023.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2023-04-23,24.0,/1,CLE
9,9.0,Jake Alu,1.0,2023.0,2023.0,0.0,-0.1,51.0,175.0,159.0,...,10.0,42.0,0.226,0.282,0.289,0.571,2023-05-09,26.0,/745H,WSN
10,10.0,Francisco Alvarez,2.0,2022.0,2023.0,0.0,1.0,128.0,437.0,394.0,...,36.0,114.0,0.208,0.284,0.439,0.723,2022-09-30,21.0,2/HD,NYM
11,11.0,Jacob Amaya,1.0,2023.0,2023.0,0.0,0.0,4.0,9.0,9.0,...,0.0,1.0,0.222,0.222,0.222,0.444,2023-06-18,24.0,/64,MIA
12,12.0,Miguel Amaya,1.0,2023.0,2023.0,0.0,0.2,53.0,156.0,131.0,...,12.0,40.0,0.214,0.329,0.359,0.688,2023-05-04,24.0,2/DH,CHC
13,13.0,Grant Anderson,1.0,2023.0,2023.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-30,26.0,/1,TEX
14,14.0,Clayton Andrews,1.0,2023.0,2023.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2023-07-01,26.0,/1,MIL
15,15.0,Gabriel Arias,2.0,2022.0,2023.0,0.0,0.1,138.0,402.0,362.0,...,36.0,129.0,0.207,0.282,0.348,0.630,2022-04-20,23.0,63/5H94D,CLE
16,16.0,Javier Assad,2.0,2022.0,2023.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,2022-08-23,25.0,1,CHC
17,17.0,Pedro Avila,4.0,2019.0,2023.0,0.0,0.0,2.0,3.0,2.0,...,0.0,1.0,0.000,0.000,0.000,0.000,2019-04-11,26.0,/1,SDP
18,18.0,Sam Bachman,1.0,2023.0,2023.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-26,23.0,/1,LAA
19,19.0,Ji Hwan Bae,2.0,2022.0,2023.0,0.0,0.1,121.0,408.0,367.0,...,32.0,98.0,0.240,0.306,0.322,0.628,2022-09-23,23.0,48/H67,PIT

In [39]:
#preview last 10 rows
df.tail(10)

,Rk,Name,Yrs,From,To,ASG,WAR/pos,G,PA,AB,...,BB,SO,BA,OBP,SLG,OPS,Debut,Age,Pos Summary,Tm
458,458.0,William Woods,1.0,2022.0,2022.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,2022-04-27,24.0,/1,NaN
459,459.0,Randy Wynne,1.0,2023.0,2023.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2023-06-25,30.0,/1,CIN
460,460.0,Masataka Yoshida,1.0,2023.0,2023.0,0.0,1.4,140.0,580.0,537.0,...,34.0,81.0,0.289,0.338,0.445,0.783,2023-03-30,29.0,7D/H,BOS
461,461.0,Danny Young,2.0,2022.0,2023.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,2022-05-09,29.0,/1,ATL
462,462.0,Jacob Young,1.0,2023.0,2023.0,0.0,0.6,33.0,121.0,107.0,...,10.0,22.0,0.252,0.322,0.336,0.658,2023-08-26,23.0,8/DH,WSN
463,463.0,Jared Young,2.0,2022.0,2023.0,0.0,-0.1,22.0,69.0,62.0,...,6.0,20.0,0.210,0.290,0.435,0.725,2022-09-16,27.0,/3DH9,CHC
464,464.0,Aneurys Zabala,1.0,2022.0,2022.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,2022-06-12,26.0,/1,NaN
465,465.0,Angel Zerpa,3.0,2021.0,2023.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,NaN,NaN,NaN,NaN,2021-09-30,23.0,/1,KCR
466,466.0,Guillermo Zuñiga,1.0,2023.0,2023.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,2023-05-02,24.0,/1,STL
467,NaN,Totals,648.0,2015.0,2023.0,4.0,65.8,8993.0,29811.0,26774.0,...,2399.0,7762.0,0.237,0.307,0.384,0.691,NaT,NaN,NaN,NaN

In [40]:
#get dimensions of dataframe
df.shape

(468, 28)

In [42]:
#get a count of each unique player age
df['Age'].value_counts()

25.0    87
26.0    74
24.0    72
23.0    63
27.0    51
28.0    39
22.0    23
21.0    15
29.0    12
30.0    10
32.0     5
31.0     5
20.0     5
33.0     2
34.0     2
19.0     1
Name: Age, dtype: int64

In [43]:
#get a count of the number of rookies on each team
df['Tm'].value_counts()

CIN    22
OAK    20
PIT    18
LAA    18
SFG    17
COL    16
SEA    15
CLE    15
KCR    15
CHC    14
TOT    14
CHW    13
ARI    13
STL    13
SDP    13
MIL    12
BOS    12
LAD    12
TBR    11
HOU    11
NYY    11
BAL    11
NYM    11
WSN    11
TEX    10
DET    10
MIN     9
MIA     9
ATL     9
TOR     7
PHI     7
Name: Tm, dtype: int64

In [49]:
#get a count of players per number of plate appearances
df['PA'].value_counts()

0.0        262
1.0          8
9.0          5
4.0          5
6.0          4
          ...
90.0         1
67.0         1
94.0         1
66.0         1
29811.0      1
Name: PA, Length: 142, dtype: int64

In [50]:
#get average number of plate appearances
df['PA'].mean()

127.67023554603854

In [48]:
#view missing data per column
df.isnull().sum()

Rk               2
Name             1
Yrs              1
From             1
To               1
ASG              1
WAR/pos          1
G                1
PA               1
AB               1
R              145
H              145
2B             145
3B             145
HR             145
RBI            145
SB             145
CS             145
BB             145
SO             145
BA             263
OBP            263
SLG            263
OPS            263
Debut            2
Age              2
Pos Summary      2
Tm              69
dtype: int64

In [61]:
#limit df to only relevant offensive statistics categories
df1 = df[["Name", "ASG", "G", "PA", "R", "H", "2B", "3B", "HR", "RBI", "SB", "CS", "BB", "SO", "BA", "OBP", 
          "SLG", "OPS", "Age", "Tm"]]

df1.head(20)

,Name,ASG,G,PA,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,Age,Tm
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Andrew Abbott,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,CIN
2,Wilyer Abreu,0.0,28.0,85.0,10.0,24.0,6.0,0.0,2.0,14.0,3.0,1.0,9.0,23.0,0.316,0.388,0.474,0.862,24.0,BOS
3,Garrett Acton,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,OAK
4,Jordyn Adams,0.0,17.0,40.0,1.0,5.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,16.0,0.128,0.125,0.128,0.253,23.0,LAA
5,Ty Adcock,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,26.0,SEA
6,Ryan Aguilar,0.0,7.0,26.0,2.0,3.0,1.0,0.0,0.0,2.0,0.0,0.0,2.0,14.0,0.136,0.231,0.182,0.413,28.0,NaN
7,Cam Alldred,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,26.0,NaN
8,Logan Allen,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.0,CLE
9,Jake Alu,0.0,51.0,175.0,14.0,36.0,2.0,1.0,2.0,16.0,5.0,1.0,10.0,42.0,0.226,0.282,0.289,0.571,26.0,WSN
10,Francisco Alvarez,0.0,128.0,437.0,54.0,82.0,13.0,0.0,26.0,64.0,2.0,0.0,36.0,114.0,0.208,0.284,0.439,0.723,21.0,NYM
11,Jacob Amaya,0.0,4.0,9.0,1.0,2.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,1.0,0.222,0.222,0.222,0.444,24.0,MIA
12,Miguel Amaya,0.0,53.0,156.0,17.0,28.0,4.0,0.0,5.0,18.0,0.0,0.0,12.0,40.0,0.214,0.329,0.359,0.688,24.0,CHC
13,Grant Anderson,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0,TEX
14,Clayton Andrews,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0,MIL
15,Gabriel Arias,0.0,138.0,402.0,45.0,75.0,16.0,1.0,11.0,31.0,4.0,4.0,36.0,129.0,0.207,0.282,0.348,0.630,23.0,CLE
16,Javier Assad,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,25.0,CHC
17,Pedro Avila,0.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000,0.000,0.000,0.000,26.0,SDP
18,Sam Bachman,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.0,LAA
19,Ji Hwan Bae,0.0,121.0,408.0,59.0,88.0,20.0,2.0,2.0,38.0,27.0,9.0,32.0,98.0,0.240,0.306,0.322,0.628,23.0,PIT

In [62]:
#filter df1 to only players with at least 10 plate appearances
df2 = df1[df1["PA"] >= 10]

df2.head(20)

,Name,ASG,G,PA,R,H,2B,3B,HR,RBI,SB,CS,BB,SO,BA,OBP,SLG,OPS,Age,Tm
2,Wilyer Abreu,0.0,28.0,85.0,10.0,24.0,6.0,0.0,2.0,14.0,3.0,1.0,9.0,23.0,0.316,0.388,0.474,0.862,24.0,BOS
4,Jordyn Adams,0.0,17.0,40.0,1.0,5.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,16.0,0.128,0.125,0.128,0.253,23.0,LAA
6,Ryan Aguilar,0.0,7.0,26.0,2.0,3.0,1.0,0.0,0.0,2.0,0.0,0.0,2.0,14.0,0.136,0.231,0.182,0.413,28.0,NaN
9,Jake Alu,0.0,51.0,175.0,14.0,36.0,2.0,1.0,2.0,16.0,5.0,1.0,10.0,42.0,0.226,0.282,0.289,0.571,26.0,WSN
10,Francisco Alvarez,0.0,128.0,437.0,54.0,82.0,13.0,0.0,26.0,64.0,2.0,0.0,36.0,114.0,0.208,0.284,0.439,0.723,21.0,NYM
12,Miguel Amaya,0.0,53.0,156.0,17.0,28.0,4.0,0.0,5.0,18.0,0.0,0.0,12.0,40.0,0.214,0.329,0.359,0.688,24.0,CHC
15,Gabriel Arias,0.0,138.0,402.0,45.0,75.0,16.0,1.0,11.0,31.0,4.0,4.0,36.0,129.0,0.207,0.282,0.348,0.630,23.0,CLE
19,Ji Hwan Bae,0.0,121.0,408.0,59.0,88.0,20.0,2.0,2.0,38.0,27.0,9.0,32.0,98.0,0.240,0.306,0.322,0.628,23.0,PIT
20,Patrick Bailey,0.0,97.0,353.0,29.0,76.0,18.0,1.0,7.0,48.0,1.0,0.0,21.0,100.0,0.233,0.285,0.359,0.644,24.0,SFG
21,Luken Baker,0.0,33.0,99.0,9.0,18.0,3.0,0.0,2.0,10.0,0.0,0.0,13.0,31.0,0.209,0.313,0.314,0.627,26.0,STL
23,Rylan Bannon,0.0,7.0,21.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.100,0.143,0.100,0.243,27.0,HOU
24,Osleivis Basabe,0.0,31.0,94.0,15.0,19.0,5.0,0.0,1.0,12.0,0.0,1.0,6.0,25.0,0.218,0.277,0.310,0.587,22.0,TBR
26,Brett Baty,0.0,119.0,431.0,45.0,82.0,12.0,0.0,11.0,39.0,2.0,0.0,31.0,117.0,0.210,0.272,0.325,0.597,23.0,NYM
28,Wynton Bernard,0.0,12.0,42.0,9.0,12.0,1.0,0.0,0.0,3.0,3.0,1.0,0.0,8.0,0.286,0.286,0.310,0.595,32.0,NaN
33,Dairon Blanco,0.0,74.0,145.0,20.0,34.0,7.0,4.0,3.0,20.0,25.0,5.0,10.0,37.0,0.260,0.322,0.443,0.764,30.0,KCR
41,Will Brennan,0.0,149.0,500.0,47.0,130.0,25.0,1.0,6.0,49.0,15.0,6.0,18.0,61.0,0.274,0.308,0.369,0.677,25.0,CLE
46,Alec Burleson,0.0,123.0,400.0,38.0,86.0,21.0,1.0,9.0,39.0,4.0,1.0,28.0,54.0,0.237,0.295,0.375,0.670,24.0,STL
47,Michael Busch,0.0,27.0,81.0,9.0,12.0,3.0,0.0,2.0,7.0,1.0,0.0,8.0,27.0,0.167,0.247,0.292,0.539,25.0,LAD
48,Lawrence Butler,0.0,42.0,129.0,10.0,26.0,4.0,0.0,4.0,10.0,0.0,0.0,4.0,35.0,0.211,0.240,0.341,0.582,22.0,OAK
50,José Caballero,0.0,104.0,280.0,37.0,51.0,9.0,1.0,4.0,26.0,26.0,3.0,28.0,66.0,0.221,0.343,0.320,0.663,26.0,SEA

In [63]:
#view missing data per column
df2.isnull().sum()

Name     0
ASG      0
G        0
PA       0
R        0
H        0
2B       0
3B       0
HR       0
RBI      0
SB       0
CS       0
BB       0
SO       0
BA       0
OBP      0
SLG      0
OPS      0
Age      1
Tm      21
dtype: int64

In [65]:
#get shape of most edited dataset (df2)
df2.shape

(176, 20)